### ISSUE TITLE
v0.17.0.0 Release Process 

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#4145]
v0.17.0.0 Release Process

Note: see https://github.com/dashpay/dash/issues/3775 for planned date of release

- [x] Update translations, see translation_process.md (#4137).
- [x] Update manpages, see gen-manpages.sh.

Before every minor and major release:
- [x] Update bips.md to account for changes since the last release (assigned @thephez) (#4149).
- [x] Update version in configure.ac (don't forget to set CLIENT_VERSION_IS_RELEASE to true) (#4148)
- [x] Write release notes (assigned @UdjinM6)
- [x] Update src/chainparams.cpp nMinimumChainWork with information from the getblockchaininfo rpc (#4087).
- [x] Update src/chainparams.cpp defaultAssumeValid with information from the getblockhash rpc (#4087).
- [x] This update should be reviewed with a reindex-chainstate with assumevalid=0 to catch any defect that causes rejection of blocks in the past history.

Before every major release:
- [x] Update hardcoded seeds (#4152). 
- [x] Update BLOCK_CHAIN_SIZE to the current size plus some overhead (#4150).
- [x] Update src/chainparams.cpp chainTxData with statistics about the transaction count and rate. Use the output of the RPC getchaintxstats, see this pull request for an example. Reviewers can verify the results by running getchaintxstats <window_block_count> <window_last_block_hash> with the window_block_count and window_last_block_hash from your output (#4087).
- [x] Update version of contrib/gitian-descriptors/*.yml: usually one'd want to do this on master after branching off the release - but be sure to at least do it before a new major release (#3512)

Tag the Release

- [x]     Tag v0.17.0.0 and push

Check CI

- [x]     Validate that CI passes 

Do Gitian Build (for unsigned binaries) and create PRs

- [x]     Pasta Gitian Build
- [x]     Udjin Gitian Build
- [x]     Dustin Gitian Build
- [x]     Thephez Gitian Build

Create Windows/OS X detached signatures (note: it might be decided skip signed binaries for RCs)
    Only once the Windows/OS X builds each have 3 matching signatures may they be signed with their respective release keys.

- [x]     Pasta creates windows detached signature and commits
- [x]     Dustin creates OS X detached signature

Update Gitian Builds with signed binaries (note: it might be decided skip signed binaries for RCs)

- [x]     Pasta Gitian Build
- [x]     Udjin Gitian Build
- [x]     Dustin Gitian Build
- [x]     Thephez Gitian Build

After 3 or more people have gitian-built and their results match:

- [x]     Create SHA256SUMS.asc for the builds
- [x]     GPG sign each download / binary
- [x]     Upload zips and installers, as well as SHA256SUMS.asc from last step, to github as github draft release. 
- [x]     Validate SHA256SUMS.asc and all binaries attached to github draft release are correct
- [x]     Notarize OS X binaries
- [x]     Release on github once dash.org is updated

Announce the release:

- [ ]      Release on Dash forum: https://www.dash.org/forum/topic/official-announcements.54/
- [x]      Optionally Discord, twitter, reddit /r/Dashpay, ... but this will usually sort out itself
- [ ]      Celebrate

**Comment by thephez** [comment]
@PastaPastaPasta See #4149 for bips.md update
