### ISSUE TITLE
Tracking issue for BLS implementation

### ISSUE THREAD

**Issue by ogabrielides** [dashpay/dash#5001]
# Tracking issue for BLS implementation

## Subtasks:
- [x] BIP9 fork implementation + helper functions
- [x] Insertion and propagation of `fLegacyScheme` flag on below parts (flag will be set regarding on fork activation status):
- - [x] BLS classes
- - [x] DKG classes: Perform all processing using the active BLS scheme
- - [x] LLMQ signing classes: sign and verify based on the active BLS scheme
- [x] New version of below txs + implemented new serialization/unserialization
- - `proRegTx`, `proUpRegTx`, `proUpServTx`, `proUpRevTx`
- [x] New version of `qcommit` + implemented new serialization/unserialization
- [x] Investigation if new serialization/unserialization is needed on DKG llmq messages (once the fork is active):
- - `qcontrib`, `qcomplaint`, `qjustify`: Update: **Not needed**
- [x] Investigation if new serialization/unserialization is needed on llmq signatures messages (once the fork is active):
- - `qsigsesann`, `qsigsinv`, `qgetsigs`, `qbsigs`, `qsigrec`, `qsigshare` Update: Not needed
- [x] Investigation if new serialization/unserialization is needed on `qdata` message (once the fork is active)
- [x] Investigation if new serialization/unserialization is needed on `dsq` and `dstx` messages (once the fork is active). Update: Signing and serialisation of objects is done using active scheme. No object versioning support.
- [x] Update unit test with expected values when using the basic BLS scheme. 
- [ ] Update: unit tests `bloom_tests`, `evo_simplifiedmns_tests` and `evo_trivialvalidation` with raw data using basic BLS scheme.
- [x] Backport [Chia-Network/bls-signatures](https://github.com/Chia-Network/bls-signatures) into [dashpay/bls-signatures](https://github.com/dashpay/bls-signatures) Update: PR already opened by @UdjinM6 (https://github.com/dashpay/bls-signatures/pull/44)
- [x] #5025

**Comment by PastaPastaPasta** [comment]
With this merged, should the params passed to masternodeblsprivkey be legacy or non-legacy keys?

**Comment by ogabrielides** [comment]
> With this merged, should the params passed to masternodeblsprivkey be legacy or non-legacy keys?

Once the v19 HF is active, then they need to be non-legacy. legacy schemes are also supported via the `protx legacy` family RPCs. Please check release notes in https://github.com/dashpay/dips/pull/122/files

**Comment by UdjinM6** [comment]
`masternodeblsprivkey` is a _privkey_ and privkey serialization is not affected by this migration afaik

**Comment by ogabrielides** [comment]
> `masternodeblsprivkey` is a _privkey_ and privkey serialization is not affected by this migration afaik

Right. I misread and thought he was talking about BLS operator key
