### ISSUE TITLE
Release Process for v21.0

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash#6081]
v21.0.0 Release Process

- [ ] **Ensure future Release Process issues are created from [the template](https://github.com/dashpay/dash/blob/develop/doc/release-process.md)**
- [x] Update translations, see translation_process.md. (@UdjinM6) #6122
- [x] Update manpages, see gen-manpages.sh. (@knst) #6125
- [x] Create main net spork hardening PR (@UdjinM6) #6140 
- [x] Allow EHF creation with v21 (@knst) #6126 
- [x] Update Security.md (@kwvg) #6117 

Before every minor and major release:
- [x] Update bips.md to account for changes since the last release (@thephez). 
- [ ] Update version in configure.ac (don't forget to set CLIENT_VERSION_IS_RELEASE to true) (@PastaPastaPasta)
- [x] Write Release Notes (@PastaPastaPasta @UdjinM6) https://github.com/dashpay/dash/pull/6144
- [x] Update src/chainparams.cpp nMinimumChainWork with information from the getblockchaininfo rpc. (@knst) (https://github.com/dashpay/dash/pull/6146)
- [x] Update src/chainparams.cpp defaultAssumeValid with information from the getblockhash rpc. (@knst) (https://github.com/dashpay/dash/pull/6146)
- [x] Update main net activation timing. 

<details>

```
        consensus.vDeployments[Consensus::DEPLOYMENT_MN_RR].bit = 10;
        consensus.vDeployments[Consensus::DEPLOYMENT_MN_RR].nStartTime = 1704067200;   // January 1, 2024
        consensus.vDeployments[Consensus::DEPLOYMENT_MN_RR].nTimeout = 1767225600; // January 1, 2026
```

</details>

- [x] This update should be reviewed with a reindex-chainstate with assumevalid=0 to catch any defect that causes rejection of blocks in the past history. (@kwvg ) (@knst)
- [x] Ensure that governance is functional (@knst)
- [ ] Ensure that testnet coinbase is partially going to platform (@knst)
- [x] Ensure all TODOs are evaluated and resolved if needed (@PastaPastaPasta to create google sheet of all) https://docs.google.com/spreadsheets/d/1pG_3Rggg8e9YPxZneVrb7c7F-x3y6sU4pZNwPRy6hoM/edit#gid=0 (dcg only) (@knst to resolve)
- [ ] Verify insight works (latte?)
- [ ] Verify p2pool works (unmaintained; no responsible party)
- [x] Notify mobile team of new protocol version

Tag the Release

- [ ]     Tag v21.0.0 and push (@PastaPastaPasta)

Check CI

- [ ]     Validate that CI passes 

Do Guix Build (for unsigned binaries) and create PRs

- [ ]     Pasta Guix Build
- [ ]     Udjin Guix Build
- [ ]     Thephez Guix Build
- [ ]     Kittywhiskers Guix Build
- [ ]     Knst Guix Build

Create Windows/OS X detached signatures (note: it might be decided skip signed binaries for RCs)
    Only once the Windows/OS X builds each have 3 matching signatures may they be signed with their respective release keys.

- [ ]     Pasta creates windows detached signature and commits
- [ ]     pasta creates OS X detached signature

Update Guix Builds with signed binaries (note: it might be decided skip signed binaries for RCs)

- [ ]     Pasta Guix Build
- [ ]     Udjin Guix Build
- [ ]     Thephez Guix Build
- [ ]     Kittywhiskers Guix Build
- [ ]     Knst Guix Build

After 3 or more people have guix-built and their results match:

- [ ]     Create SHA256SUMS.asc for the builds
- [ ]     GPG sign each download / binary
- [ ]     Upload zips and installers, as well as SHA256SUMS.asc from last step, to github as github draft release. 
- [ ]     Validate SHA256SUMS.asc and all binaries attached to github draft release are correct
- [ ]     Notarize OS X binaries
- [ ]     Release on github
- [ ]     Update website
- [ ]     Ensure that docker hub images are up to date

Announce the release:

- [ ]      Release on Dash forum: https://www.dash.org/forum/topic/official-announcements.54/ (@PastaPastaPasta)
- [ ]      Optionally Discord, twitter, reddit /r/Dashpay, post in slack... but this will usually sort out itself
- [ ]      Celebrate

After the release 

- [ ]     Submit patches to BTCPay to ensure they use latest / compatible version see https://github.com/dashpay/dash/issues/4211#issuecomment-966608207 (@strophy ?)
- [ ] Fast forward master; merge master into develop
- [ ] Make develop branch the default branch in Github (note this is a potentially breaking change for people who simply clone the repo and build without specifying a branch)

Additional Items
- [ ] Prepare release blog post (necessary so we have a permalink to use on twitter, reddit, etc.)
- [ ] Prepare product brief (major versions only?) (@thephez; need to talk with marina and publish this asap)
- [ ] Prepare a release announcement tweet (tell Marina)
- [ ] Follow-up tweets with any important block heights for consensus changes (Marina again)
- [ ] Post on reddit
- [ ] Update docs (readme and RTD) (@thephez)
- [ ] Test Docker build runs without errors in Dashmate (@shumkov)
- [ ] Add new Release Process items to in repo release process document (@knst)

**Comment by thephez** [comment]
@PastaPastaPasta I'm not aware of any changes that are required in `bips.md`

**Comment by thephez** [comment]
When we add new special transactions, we need to [open an issue on the dashcore-lib repo](https://github.com/dashpay/dashcore-lib/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=) so it gets updated.
